from typing import Dict, Tuple                                                                                                                                                                                      
import torch                                                                                                                                                                                                        
from torch import Tensor, nn                                                                                                                                                                                        
from mmdet.registry import MODELS                                                                                                                                                                                   
from mmdet.structures import OptSampleList                                                                                                                                                                          
from mmdet.utils import OptConfigType                                                                                                                                                                               
from .dino import DINO                                                                                                                                                                                              
                                                                                                                                                                                                                    
@MODELS.register_module()                                                                                                                                                                                           
class UCFDINO(DINO):                                                                                                                                                                                                
    """UCF-DINO: Underwater-enhanced DINO with dual-stream architecture                                                                                                                                             
                                                                                                                                                                                                                    
    Args:                                                                                                                                                                                                           
        enhancer (dict): Config for image enhancement module                                                                                                                                                        
        fusion_in_encoder (bool): Whether to fuse dual streams in encoder                                                                                                                                           
        *args, **kwargs: Arguments for DINO                                                                                                                                                                         
    """                                                                                                                                                                                                             
                                                                                                                                                                                                                    
    def __init__(self,                                                                                                                                                                                              
                *args,                                                                                                                                                                                             
                enhancer: OptConfigType = None,                                                                                                                                                                    
                fusion_in_encoder: bool = True,                                                                                                                                                                    
                **kwargs) -> None:                                                                                                                                                                                 
        # 在调用父类 __init__ 之前设置这些属性
        # 因为父类 __init__ 会调用 _init_layers()，而 _init_layers 需要访问这些属性
        self.fusion_in_encoder = fusion_in_encoder
        self.enhancer = None  # 先初始化为 None

        super().__init__(*args, **kwargs)                                                                                                                                                                           
                                                                                                                                                                                                                    
        # 初始化图像增强器                                                                                                                                                                                          
        if enhancer is not None:                                                                                                                                                                                    
            self.enhancer = MODELS.build(enhancer)                                                                                                                                                                  
            # 冻结增强器参数（如果需要）                                                                                                                                                                            
            for param in self.enhancer.parameters():                                                                                                                                                                
                param.requires_grad = False                                                                                                                                                                         
        else:                                                                                                                                                                                                       
            self.enhancer = None                                                                                                                                                                                    
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
    def _init_layers(self) -> None:                                                                                                                                                                                 
        """Initialize layers with dual-stream support."""                                                                                                                                                           
        super()._init_layers()                                                                                                                                                                                      
                                                                                                                                                                                                                    
        # 如果需要在编码器中融合，添加融合模块                                                                                                                                                                      
        if self.fusion_in_encoder:                                                                                                                                                                                  
            self._init_fusion_modules()                                                                                                                                                                             
                                                                                                                                                                                                                    
    def _init_fusion_modules(self):                                                                                                                                                                                 
        """Initialize fusion modules for dual-stream features."""                                                                                                                                                   
        # 双向交叉注意力模块                                                                                                                                                                                        
        self.cross_attn_raw_to_enh = nn.ModuleList()                                                                                                                                                                
        self.cross_attn_enh_to_raw = nn.ModuleList()                                                                                                                                                                
        self.fusion_norms = nn.ModuleList()                                                                                                                                                                         
                                                                                                                                                                                                                    
        # 为每个特征层级添加融合模块                                                                                                                                                                                
        for _ in range(self.num_feature_levels):                                                                                                                                                                    
            # 原始流 -> 增强流的交叉注意力                                                                                                                                                                          
            self.cross_attn_raw_to_enh.append(                                                                                                                                                                      
                nn.MultiheadAttention(                                                                                                                                                                              
                    self.embed_dims,                                                                                                                                                                                
                    num_heads=8,                                                                                                                                                                                    
                    dropout=0.1,                                                                                                                                                                                    
                    batch_first=True                                                                                                                                                                                
                )                                                                                                                                                                                                   
            )                                                                                                                                                                                                       
            # 增强流 -> 原始流的交叉注意力                                                                                                                                                                          
            self.cross_attn_enh_to_raw.append(                                                                                                                                                                      
                nn.MultiheadAttention(                                                                                                                                                                              
                    self.embed_dims,                                                                                                                                                                                
                    num_heads=8,                                                                                                                                                                                    
                    dropout=0.1,                                                                                                                                                                                    
                    batch_first=True                                                                                                                                                                                
                )                                                                                                                                                                                                   
            )                                                                                                                                                                                                       
            self.fusion_norms.append(nn.LayerNorm(self.embed_dims))                                                                                                                                                 
                                                                                                                                                                                                                    
        # 门控融合模块                                                                                                                                                                                              
        self.gate_fusion = GatedFusion(self.embed_dims)                                                                                                                                                             
                                                                                                                                                                                                                    
    def extract_feat(self, batch_inputs: Tensor) -> Tuple[Tensor]:                                                                                                                                                  
        """Extract features with dual-stream processing.                                                                                                                                                            
                                                                                                                                                                                                                    
        Args:                                                                                                                                                                                                       
            batch_inputs (Tensor): Input images, shape (bs, 3, H, W)                                                                                                                                                
                                                                                                                                                                                                                    
        Returns:                                                                                                                                                                                                    
            Tuple[Tensor]: Multi-scale features from both streams                                                                                                                                                   
        """                                                                                                                                                                                                         
        # 原始图像特征提取                                                                                                                                                                                          
        raw_feats = self.backbone(batch_inputs)                                                                                                                                                                     
        if self.with_neck:                                                                                                                                                                                          
            raw_feats = self.neck(raw_feats)                                                                                                                                                                        
                                                                                                                                                                                                                    
        # 如果有增强器，提取增强图像特征                                                                                                                                                                            
        if self.enhancer is not None:                                                                                                                                                                               
            enhanced_imgs = self.enhancer(batch_inputs)                                                                                                                                                             
            enh_feats = self.backbone(enhanced_imgs)                                                                                                                                                                
            if self.with_neck:                                                                                                                                                                                      
                enh_feats = self.neck(enh_feats)                                                                                                                                                                    
                                                                                                                                                                                                                    
            return raw_feats, enh_feats                                                                                                                                                                             
        else:                                                                                                                                                                                                       
            return raw_feats, raw_feats                                                                                                                                                                             
                                                                                                                                                                                                                    
    def forward_transformer(self,                                                                                                                                                                                   
                        img_feats: Tuple[Tensor],                                                                                                                                                                 
                        batch_data_samples: OptSampleList = None) -> Dict:                                                                                                                                        
        """Forward with dual-stream fusion.                                                                                                                                                                         
                                                                                                                                                                                                                    
        Args:                                                                                                                                                                                                       
            img_feats: Tuple of (raw_feats, enhanced_feats)                                                                                                                                                         
        """                                                                                                                                                                                                         
        # 解包双流特征                                                                                                                                                                                              
        if isinstance(img_feats[0], tuple):                                                                                                                                                                         
            raw_feats, enh_feats = img_feats                                                                                                                                                                        
        else:                                                                                                                                                                                                       
            raw_feats = enh_feats = img_feats                                                                                                                                                                       
                                                                                                                                                                                                                    
        # Pre-transformer处理（位置编码等）                                                                                                                                                                         
        encoder_inputs_dict_raw, decoder_inputs_dict = self.pre_transformer(                                                                                                                                        
            raw_feats, batch_data_samples)                                                                                                                                                                          
                                                                                                                                                                                                                    
        if self.enhancer is not None:                                                                                                                                                                               
            encoder_inputs_dict_enh, _ = self.pre_transformer(                                                                                                                                                      
                enh_feats, batch_data_samples)                                                                                                                                                                      
        else:                                                                                                                                                                                                       
            encoder_inputs_dict_enh = encoder_inputs_dict_raw                                                                                                                                                       
                                                                                                                                                                                                                    
        # 双流编码器前向传播                                                                                                                                                                                        
        encoder_outputs_dict = self.forward_dual_stream_encoder(                                                                                                                                                    
            encoder_inputs_dict_raw,                                                                                                                                                                                
            encoder_inputs_dict_enh                                                                                                                                                                                 
        )                                                                                                                                                                                                           
                                                                                                                                                                                                                    
        # Decoder处理                                                                                                                                                                                               
        tmp_dec_in, head_inputs_dict = self.pre_decoder(                                                                                                                                                            
            **encoder_outputs_dict,                                                                                                                                                                                 
            batch_data_samples=batch_data_samples                                                                                                                                                                   
        )                                                                                                                                                                                                           
        decoder_inputs_dict.update(tmp_dec_in)                                                                                                                                                                      
                                                                                                                                                                                                                    
        decoder_outputs_dict = self.forward_decoder(**decoder_inputs_dict)                                                                                                                                          
        head_inputs_dict.update(decoder_outputs_dict)                                                                                                                                                               
                                                                                                                                                                                                                    
        return head_inputs_dict                                                                                                                                                                                     
                                                                                                                                                                                                                    
    def forward_dual_stream_encoder(self,                                                                                                                                                                           
                                    encoder_inputs_raw: Dict,                                                                                                                                                        
                                    encoder_inputs_enh: Dict) -> Dict:                                                                                                                                               
        """Forward dual-stream encoder with cross-attention fusion.                                                                                                                                                 
                                                                                                                                                                                                                    
        Args:                                                                                                                                                                                                       
            encoder_inputs_raw: Encoder inputs for raw stream                                                                                                                                                       
            encoder_inputs_enh: Encoder inputs for enhanced stream                                                                                                                                                  
                                                                                                                                                                                                                    
        Returns:                                                                                                                                                                                                    
            Dict: Fused encoder outputs                                                                                                                                                                             
        """                                                                                                                                                                                                         
        # 分别通过编码器                                                                                                                                                                                            
        encoder_outputs_raw = self.forward_encoder(**encoder_inputs_raw)                                                                                                                                            
        encoder_outputs_enh = self.forward_encoder(**encoder_inputs_enh)                                                                                                                                            
                                                                                                                                                                                                                    
        if not self.fusion_in_encoder or self.enhancer is None:                                                                                                                                                     
            # 如果不融合，直接返回原始流                                                                                                                                                                            
            return encoder_outputs_raw                                                                                                                                                                              
                                                                                                                                                                                                                    
        # 双向交叉注意力融合                                                                                                                                                                                        
        memory_raw = encoder_outputs_raw['memory']                                                                                                                                                                  
        memory_enh = encoder_outputs_enh['memory']                                                                                                                                                                  
        spatial_shapes = encoder_outputs_raw['spatial_shapes']                                                                                                                                                      
                                                                                                                                                                                                                    
        # 融合特征                                                                                                                                                                                                  
        memory_fused = self.fuse_dual_stream_features(                                                                                                                                                              
            memory_raw, memory_enh, spatial_shapes                                                                                                                                                                  
        )                                                                                                                                                                                                           
                                                                                                                                                                                                                    
        # 更新输出                                                                                                                                                                                                  
        encoder_outputs_raw['memory'] = memory_fused                                                                                                                                                                
        return encoder_outputs_raw                                                                                                                                                                                  
                                                                                                                                                                                                                    
    def fuse_dual_stream_features(self,                                                                                                                                                                             
                                memory_raw: Tensor,                                                                                                                                                                
                                memory_enh: Tensor,                                                                                                                                                                
                                spatial_shapes: Tensor) -> Tensor:                                                                                                                                                 
        """Fuse dual-stream features using bidirectional cross-attention.                                                                                                                                           
                                                                                                                                                                                                                    
        Args:                                                                                                                                                                                                       
            memory_raw: Raw stream features (bs, num_tokens, C)                                                                                                                                                     
            memory_enh: Enhanced stream features (bs, num_tokens, C)                                                                                                                                                
            spatial_shapes: Spatial shapes of multi-scale features                                                                                                                                                  
                                                                                                                                                                                                                    
        Returns:                                                                                                                                                                                                    
            Tensor: Fused features                                                                                                                                                                                  
        """                                                                                                                                                                                                         
        bs, num_tokens, C = memory_raw.shape                                                                                                                                                                        
                                                                                                                                                                                                                    
        # 按照空间尺度分割特征                                                                                                                                                                                      
        start_idx = 0                                                                                                                                                                                               
        fused_features = []                                                                                                                                                                                         
                                                                                                                                                                                                                    
        for lvl, (H, W) in enumerate(spatial_shapes):                                                                                                                                                               
            num_tokens_lvl = H * W                                                                                                                                                                                  
            end_idx = start_idx + num_tokens_lvl                                                                                                                                                                    
                                                                                                                                                                                                                    
            # 提取当前层级的特征                                                                                                                                                                                    
            raw_lvl = memory_raw[:, start_idx:end_idx, :]                                                                                                                                                           
            enh_lvl = memory_enh[:, start_idx:end_idx, :]                                                                                                                                                           
                                                                                                                                                                                                                    
            # 双向交叉注意力                                                                                                                                                                                        
            # 1. 增强流作为query，原始流作为key/value                                                                                                                                                               
            attn_out_enh, _ = self.cross_attn_raw_to_enh[lvl](                                                                                                                                                      
                query=enh_lvl,                                                                                                                                                                                      
                key=raw_lvl,                                                                                                                                                                                        
                value=raw_lvl                                                                                                                                                                                       
            )                                                                                                                                                                                                       
                                                                                                                                                                                                                    
            # 2. 原始流作为query，增强流作为key/value                                                                                                                                                               
            attn_out_raw, _ = self.cross_attn_enh_to_raw[lvl](                                                                                                                                                      
                query=raw_lvl,                                                                                                                                                                                      
                key=enh_lvl,                                                                                                                                                                                        
                value=enh_lvl                                                                                                                                                                                       
            )                                                                                                                                                                                                       
                                                                                                                                                                                                                    
            # 残差连接和归一化                                                                                                                                                                                      
            fused_lvl = self.fusion_norms[lvl](                                                                                                                                                                     
                raw_lvl + attn_out_raw + enh_lvl + attn_out_enh                                                                                                                                                     
            )                                                                                                                                                                                                       
                                                                                                                                                                                                                    
            fused_features.append(fused_lvl)                                                                                                                                                                        
            start_idx = end_idx                                                                                                                                                                                     
                                                                                                                                                                                                                    
        # 拼接所有层级                                                                                                                                                                                              
        memory_fused = torch.cat(fused_features, dim=1)                                                                                                                                                             
                                                                                                                                                                                                                    
        return memory_fused                                                                                                                                                                                         
                                                                                                                                                                                                                    
                                                                                                                                                                                                                    
class GatedFusion(nn.Module):                                                                                                                                                                                       
    """门控融合模块"""                                                                                                                                                                                              
    def __init__(self, embed_dims):                                                                                                                                                                                 
        super().__init__()                                                                                                                                                                                          
        self.gate_conv = nn.Linear(embed_dims * 2, embed_dims)                                                                                                                                                      
                                                                                                                                                                                                                    
    def forward(self, feat1, feat2):                                                                                                                                                                                
        """                                                                                                                                                                                                         
        Args:                                                                                                                                                                                                       
            feat1, feat2: (bs, num_tokens, C)                                                                                                                                                                       
        """                                                                                                                                                                                                         
        gate = torch.sigmoid(                                                                                                                                                                                       
            self.gate_conv(torch.cat([feat1, feat2], dim=-1))                                                                                                                                                       
        )                                                                                                                                                                                                           
        return feat1 + gate * feat2