import torch                                                                                                                                                                                                        
import torch.nn as nn                                                                                                                                                                                               
import torch.nn.functional as F                                                                                                                                                                                     
from mmdet.registry import MODELS                                                                                                                                                                                   
                                                                                                                                                                                                                    
@MODELS.register_module()                                                                                                                                                                                           
class UnderwaterImageEnhancer(nn.Module):                                                                                                                                                                           
    """水下图像增强器                                                                                                                                                                                               
                                                                                                                                                                                                                    
    可以使用预训练的增强模型，如：                                                                                                                                                                                  
    - UWCNN                                                                                                                                                                                                         
    - Water-Net                                                                                                                                                                                                     
    - FUnIE-GAN                                                                                                                                                                                                     
    或简单的颜色校正                                                                                                                                                                                                
    """                                                                                                                                                                                                             
                                                                                                                                                                                                                    
    def __init__(self,                                                                                                                                                                                              
                method='color_correction',                                                                                                                                                                         
                pretrained=None):                                                                                                                                                                                  
        super().__init__()                                                                                                                                                                                          
        self.method = method                                                                                                                                                                                        
                                                                                                                                                                                                                    
        if method == 'color_correction':                                                                                                                                                                            
            # 简单的颜色校正网络                                                                                                                                                                                    
            self.enhance_net = nn.Sequential(                                                                                                                                                                       
                nn.Conv2d(3, 32, 3, padding=1),                                                                                                                                                                     
                nn.ReLU(inplace=True),                                                                                                                                                                              
                nn.Conv2d(32, 32, 3, padding=1),                                                                                                                                                                    
                nn.ReLU(inplace=True),                                                                                                                                                                              
                nn.Conv2d(32, 3, 3, padding=1),                                                                                                                                                                     
                nn.Tanh()                                                                                                                                                                                           
            )                                                                                                                                                                                                       
        elif method == 'identity':                                                                                                                                                                                  
            # 不做增强，用于消融实验                                                                                                                                                                                
            self.enhance_net = nn.Identity()                                                                                                                                                                        
        else:                                                                                                                                                                                                       
            raise NotImplementedError(f"Method {method} not implemented")                                                                                                                                           
                                                                                                                                                                                                                    
        if pretrained is not None:                                                                                                                                                                                  
            self.load_pretrained(pretrained)                                                                                                                                                                        
                                                                                                                                                                                                                    
    def forward(self, x):                                                                                                                                                                                           
        """                                                                                                                                                                                                         
        Args:                                                                                                                                                                                                       
            x: (bs, 3, H, W) 原始图像                                                                                                                                                                               
        Returns:                                                                                                                                                                                                    
            enhanced: (bs, 3, H, W) 增强后的图像                                                                                                                                                                    
        """                                                                                                                                                                                                         
        if self.method == 'identity':                                                                                                                                                                               
            return x                                                                                                                                                                                                
                                                                                                                                                                                                                    
        # 颜色校正                                                                                                                                                                                                  
        residual = self.enhance_net(x)                                                                                                                                                                              
        enhanced = x + residual                                                                                                                                                                                     
        enhanced = torch.clamp(enhanced, 0, 1)                                                                                                                                                                      
                                                                                                                                                                                                                    
        return enhanced                                                                                                                                                                                             
                                                                                                                                                                                                                    
    def load_pretrained(self, checkpoint_path):                                                                                                                                                                     
        """加载预训练权重"""                                                                                                                                                                                        
        checkpoint = torch.load(checkpoint_path, map_location='cpu')                                                                                                                                                
        self.load_state_dict(checkpoint, strict=False)